name: namekocf
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip==20.0.2
  - pip:
    - dnspython==1.16.0
    - nameko==v3.0.0-rc8
    - marshmallow==2.19.2
    - psycopg2-binary==2.8.2
    - nameko-sqlalchemy==1.5.0
    - alembic==1.0.10
    - redis==3.2.1
